### ISSUE TITLE
Unable to find "h5 files"

### ISSUE THREAD

**Issue by achievementtoo** [jnzs1836/ERA-VSum#1]
Hello. I'm a university student in Japan, and researching unsupervised video summarization.
Thanks to your research and codes, I could learn about state-of-the-art method of video summarization.
Then, I have trouble in finding "h5 files", which is necessary for "tvsum_h5_path" in Qualitative Analysis.ipynb.
Also, what is the purpose of "h5 files"? Or, how can I make the files?
If possible, I'd like you to tell me about how to find the files.

OS : Ubuntu 18.04
python version : 3.8.12
virtual environment : venv (virtualenv)

Sincerely yours,
achievementtoo

**Comment by jnzs1836** [comment]
Hi achievementtoo,

 The h5 files are the dataset files containing the video features and annotations. The files are available on 

https://github.com/KaiyangZhou/pytorch-vsumm-reinforce

Sorry I did not make it clear in the document. I will fix it in next update soon.

Guande

**Comment by achievementtoo** [comment]
Hi Guande,

Thank you for your quick response.
I understand the meaning and location of the files.

Thanks to your help, I could solve the problem.

Kind regards,
achievementtoo
