### ISSUE TITLE
About "Qualitative Analysis.ipynb"

### ISSUE THREAD

**Issue by achievementtoo** [jnzs1836/ERA-VSum#2]
Hello Guande

I'm a Japanese university student, who posted an issue a few days ago.
Now, I have three questions in your code.

First, I couldn't find "score_directory" and "video_directory" in the second cell.
Also, "read_video_meta function" is not defined.

Second, I had KeyError about "video_key = "video_42"" in the fifth cell. 
Where can I find this "video_42"? 

Third, where is the "checkpoints_path" in "generate_scores.py", script directory?

I'm sorry for asking many questions.
I'd like you to answer my questions, when it's convenient for you.

Sincerely,
achievementtoo

**Comment by jnzs1836** [comment]
I am so sorry for the late reply,

1. score_dir is the directory path, where you put your generated score files. 
2. video directory is the directory, where you put the dataset videos. The videos can be downloaded from [there](https://github.com/yalesong/tvsum)
3. "video_42" is the video key in the h5 file. You can find it in the dataset file, which can be downloaded from [there](https://github.com/KaiyangZhou/pytorch-vsumm-reinforce)
4. generate_scores.py is in the root of the repository. checkpoints_path is where you put your trained checkpoint file. This path should be same with the save_dir of the training script (in ./scripts/train_tvsum.sh)

Feel free to contact me. You can also email me at [guandewu@nyu.edu](mailto:guandewu@nyu.edu).

**Comment by achievementtoo** [comment]
No problem. Thank you for replying.

Thanks to your answer, I could solve my problems.
If there are more questions, I'll email you.
